### ISSUE TITLE
Analog stick not working in EGUI with DualShock 3

### ISSUE THREAD

**Issue by ToughGuyKunio** [luxtorpeda-dev/luxtorpeda#121]
### Linux Distribution

Manjaro

### Luxtorpeda Version

Test Build Luxtorpeda #88

### Bug description

Don't know how I missed this before but only the D-pad works in the GUI, the left analog stick doesn't work.

### Steps To Reproduce

1. Launch game that opens EGUI
2. Try to move selection using analog stick

### Expected Behavior

Both the d-pad and the analog stick should be able to navigate the EGUI menu

**Comment by d10sfan** [comment]
@ToughGuyKunio 

This is by design, currently no analog stick is supported. The client uses sdl2 other than for steam controllers, where it uses a usb interface. With sdl2, all controller support is the same across different types as long as it's supported in their "GameController" interface. The thing I'm adding is the glyphs.

Currently, the left analog stick is not supported because unlike the d-pad where it's a simple up down left right, the analog stick has just directions and motions, so it's much more work to detect what's actually wanted. I will see about investigating this sometime in the future.

**Comment by d10sfan** [comment]
@ToughGuyKunio Added a change that adds support for this in: https://github.com/luxtorpeda-dev/luxtorpeda/pull/119
