### ISSUE TITLE
Show icon in taskbar

### ISSUE THREAD

**Issue by ThibaultLemaire** [luxtorpeda-dev/luxtorpeda#165]
### Feature Request

The GUI windows created are not visible in the taskbar or KDE's desktop grid. Making it hard to manage them (move to another virtual desktop for example).

### Solution

It would be nice to have all luxtorpeda windows register correctly within the window manager.

**Comment by d10sfan** [comment]
@ThibaultLemaire That was because of it being set as an sdl utility window, which hides the taskbar window, among other things. I don't think it'd hurt anything to remove that and show the taskbar icon, although I will need to see about an actual icon if that is done, seeing if there's an icon I can find online that's usable for the project.

**Comment by ThibaultLemaire** [comment]
Ah right, the icon. Not much of an artist, but I might try to trace something in Inkscape based on the pictures in [the wikipedia article](https://en.wikipedia.org/wiki/Luxtorpeda) ? Or we might make a call for contributions

**Comment by d10sfan** [comment]
@ThibaultLemaire I found an icon in the public domain that should work and created a PR related to this: https://github.com/luxtorpeda-dev/luxtorpeda/pull/166

If you'd like to try it, let me know what you think. If this works, I'll probably make a new release with these two changes soon.

I needed to add sdl2 image as a dependency, which is included in the steam runtime. I edited the nix pkgs script you included, so feel free to test that and make sure it still builds.

There's a compiled build here: https://github.com/luxtorpeda-dev/luxtorpeda/actions/runs/2858491911
