### ISSUE TITLE
Please allow for Luxtorpeda to install its default configs over a customized one.

### ISSUE THREAD

**Issue by landwalker000** [luxtorpeda-dev/luxtorpeda#201]
### Feature Request

Hello, 

Can the option to have to have default config files be added to override a customized one?

Basically I changed one setting in Jedi Outcast in the menu of the game. I didn't know you were not supposed to touch the settings menu. Now I can't get the original setting that Luxtorpeda set.

I have tried uninstalling, deleting the game files, deleting the compat files, turing off steam cloud, and using cryotools to remove the game data and still when I load up the game with Luxtorpeda I get the same messed up config. 

### Solution

Can an option be added to reset the configs to Luxtorpeda's configs? Or can I download them from somewhere and just manually override the current config?

**Comment by d10sfan** [comment]
Most likely the game has a config file in the user directory that isnt being affected by deleting the game files. This is fairly normal for Linux games and other apps.

For example for openjk, that would be here: ~/.local/share/openjk. If you delete that, any defaults would be set back

What system are you running on?

**Comment by landwalker000** [comment]
I am using a steam deck the latest stable build. 

I will try and find the folder you mentioned.

**Comment by landwalker000** [comment]
I cannot find a folder called openjk. Should it be under home/deck/local/share? I tried searching for openjk in Dolphin but the search never finishes.

**Comment by landwalker000** [comment]
Could you maybe paste the cfg file here or make it available so I can just copy it over to the base folder?

**Comment by landwalker000** [comment]
Okay, I did find .local. I did not know it was a hidden file but deleting the folder did reset the config. You might want to include this in your FAQ. I doubt I will be the only person who needs the config file reset.

**Comment by d10sfan** [comment]
Glad that cleared it up for you! 

The config getting broken because of in-game UI normally shouldn't happen, but some of the games setting menus that the engines are using don't seem to understand certain cvars, so clearing the config can help.

I've added a note on this issue (https://github.com/luxtorpeda-dev/luxtorpeda/issues/179) related to researching a way to provide a button that can clear the user config for a particular engine. Note that each engine has a unique place to store, so it'd be special for each engine. But when that issue is completed, that feature should be available. 

Let me know if you have any further issues or questions. Thanks for the issue!

**Comment by landwalker000** [comment]
Thanks for the help. Changing the settings didn't break the game but once you change anything there's no way to go back to the stock setting without deleting the folder in .local.  Also, when using a Steam Deck it is pretty easy to accidently hit a setting and change it.
